"""
Option B claim-check: given one finalized rep sentence + the contract clauses,
decide whether the sentence contradicts a clause.

Hallucination rule: clause text shown to users is ALWAYS fetched by clause_id
from the contract (fake_contract.json), NEVER generated by the LLM. The LLM
only picks a verdict + a clause_id (validated against the real contract) +
a confidence; it never gets to invent clause wording that reaches the user.

Verified 2026-09-14 against the installed google-genai==2.22.0 SDK and
https://ai.google.dev/gemini-api/docs :
- Model id: "gemini-2.5-flash" — official docs describe it as "best
  price-performance model for low-latency, high-volume tasks" and it appears
  in the Free Tier / rate-limit tables at
  https://ai.google.dev/gemini-api/docs/models and
  https://ai.google.dev/gemini-api/docs/rate-limits
- Call shape confirmed by introspecting the installed SDK directly (ground
  truth beats a fetched doc summary):
    client.models.generate_content(
        model=..., contents=...,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=<dict>,
            http_options=types.HttpOptions(timeout=<ms>),
        ),
    )
  per https://ai.google.dev/gemini-api/docs/structured-output
"""
from __future__ import annotations

import json
import os
import time
from typing import Any, Optional

DEFAULT_MODEL = os.environ.get("CLAUSECATCHER_GEMINI_MODEL", "gemini-2.5-flash")
CONFIDENCE_MIN = 0.6  # contradiction below this confidence downgrades to "unclear"
TIMEOUT_MS = 8000
_VERDICTS = ("contradiction", "consistent", "unclear")

_RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "verdict": {"type": "string", "enum": list(_VERDICTS)},
        "clause_id": {"type": "string", "nullable": True},
        "confidence": {"type": "number"},
    },
    "required": ["verdict", "clause_id", "confidence"],
}


def _build_prompt(sentence: str, clauses: list[dict]) -> str:
    clause_lines = "\n".join(
        f'- id="{c["section_number"]}" title="{c["title"]}": {c["literal_text"]}'
        for c in clauses
    )
    return f"""You are a contract compliance checker reviewing one sentence from a sales call transcript against the signed contract's clauses.

Contract clauses:
{clause_lines}

Rep sentence: "{sentence}"

Decide whether the sentence CONTRADICTS a clause's literal terms.
- "contradiction": the sentence states or implies something that conflicts with one clause (wrong price, wrong seat count, wrong notice period, promises a term the clause forbids, etc). Paraphrases count ("knock ten percent off" contradicts "no verbal discounting").
- "consistent": the sentence matches or is compatible with one clause's literal terms.
- "unclear": off-topic small talk, vague/hedged language with no concrete claim, or doesn't clearly match any clause.

Rules:
- If verdict is "contradiction" or "consistent", clause_id MUST be exactly one of the id values shown above.
- If verdict is "unclear", clause_id MUST be null.
- confidence is a number from 0.0 to 1.0: your certainty in the verdict.

Respond with ONLY the JSON object matching the schema. Do not invent or quote clause wording beyond the ids given."""


def check_claim(
    sentence: str,
    clauses: list[dict],
    *,
    client: Any = None,
    model: Optional[str] = None,
) -> dict:
    """Check one rep sentence against contract clauses for contradiction.

    Never raises. On any error (network, timeout, 429, bad JSON, schema
    mismatch) returns verdict "unclear" with `error` set — accuse-only-on-
    positive-evidence: an error is never treated as evidence of a violation.
    """
    model = model or DEFAULT_MODEL
    t0 = time.monotonic()
    valid_ids = {c["section_number"] for c in clauses}
    result: dict = {
        "verdict": "unclear",
        "clause_id": None,
        "confidence": 0.0,
        "latency_ms": 0.0,
        "model": model,
        "error": None,
    }
    try:
        if client is None:
            from google import genai

            key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
            if not key:
                raise RuntimeError("no GEMINI_API_KEY/GOOGLE_API_KEY set in environment")
            client = genai.Client(api_key=key)  # ponytail: key never stored on result/log

        from google.genai import types

        response = client.models.generate_content(
            model=model,
            contents=_build_prompt(sentence, clauses),
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=_RESPONSE_SCHEMA,
                temperature=0,
                http_options=types.HttpOptions(timeout=TIMEOUT_MS),
            ),
        )
        data = json.loads(response.text)

        verdict = data.get("verdict")
        clause_id = data.get("clause_id")
        try:
            confidence = float(data.get("confidence", 0.0))
        except (TypeError, ValueError):
            confidence = 0.0
        confidence = max(0.0, min(1.0, confidence))

        if verdict not in _VERDICTS:
            verdict, clause_id = "unclear", None
        if clause_id not in valid_ids:
            clause_id = None
            if verdict != "unclear":
                verdict = "unclear"
        if verdict == "contradiction" and confidence < CONFIDENCE_MIN:
            verdict = "unclear"

        result["verdict"] = verdict
        result["clause_id"] = clause_id
        result["confidence"] = confidence
    except Exception as exc:  # noqa: BLE001 - intentional catch-all, see docstring
        result["verdict"] = "unclear"
        result["clause_id"] = None
        result["confidence"] = 0.0
        result["error"] = f"{type(exc).__name__}: {exc}"
    finally:
        result["latency_ms"] = (time.monotonic() - t0) * 1000.0
    return result


def demo() -> None:
    """ponytail self-check: no network, uses a stub client."""

    class _Resp:
        def __init__(self, text):
            self.text = text

    class _Models:
        def generate_content(self, model, contents, config):
            return _Resp(json.dumps({"verdict": "contradiction", "clause_id": "3.1", "confidence": 0.95}))

    class _Client:
        models = _Models()

    clauses = [{"section_number": "3.1", "title": "Pricing", "literal_text": "Flat $48,000, no discounting."}]
    out = check_claim("We'll knock ten percent off.", clauses, client=_Client())
    assert out["verdict"] == "contradiction"
    assert out["clause_id"] == "3.1"
    assert out["error"] is None

    # bad clause_id -> unclear
    class _Models2:
        def generate_content(self, model, contents, config):
            return _Resp(json.dumps({"verdict": "contradiction", "clause_id": "9.9", "confidence": 0.9}))

    class _Client2:
        models = _Models2()

    out2 = check_claim("x", clauses, client=_Client2())
    assert out2["verdict"] == "unclear" and out2["clause_id"] is None

    # exception -> unclear + error, no raise
    class _Models3:
        def generate_content(self, model, contents, config):
            raise TimeoutError("boom")

    class _Client3:
        models = _Models3()

    out3 = check_claim("x", clauses, client=_Client3())
    assert out3["verdict"] == "unclear" and out3["error"] is not None
    print("claim_check.py demo: OK")


if __name__ == "__main__":
    demo()
