"""Claim-check: given one finalized rep sentence + contract clauses, decide
whether the sentence contradicts a clause.

Ported from spikes/claim_check/claim_check.py (kept verbatim: hallucination
rule + all safety behaviors -- clause_id must exist in the contract, low
confidence contradictions downgrade to unclear, any error/429/timeout ->
unclear, never raises).

Hallucination rule: clause text shown to users is ALWAYS fetched by clause_id
from the contract, NEVER generated by the LLM. The LLM only picks a
verdict + a clause_id (validated against the real contract) + a confidence;
it never gets to invent clause wording that reaches the user.

Model default: gemini-2.5-flash is NOT used here. Per user memory
(measured live): the free tier allows only ~20 requests/day per full
"flash" model per project -- one demo session can exhaust it -- and
"-flash-lite" models have much higher free-tier limits. Verified against
https://ai.google.dev/gemini-api/docs/models on 2026-09-15 (WebFetch):
"gemini-3.5-flash-lite" is listed there as the current, Stable, top
flash-lite model id. Override via env CLAUSECATCHER_GEMINI_MODEL.
"""
from __future__ import annotations

import json
import logging
import os
import time
from typing import Any, Callable, Optional

logger = logging.getLogger("clausecatcher")

DEFAULT_MODEL = os.environ.get("CLAUSECATCHER_GEMINI_MODEL", "gemini-3.5-flash-lite")
CONFIDENCE_MIN = 0.6  # contradiction below this confidence downgrades to "unclear"
TIMEOUT_MS = 8000
_VERDICTS = ("contradiction", "consistent", "unclear")

_RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "verdict": {"type": "string", "enum": list(_VERDICTS)},
        "clause_id": {"type": "string", "nullable": True},
        "confidence": {"type": "number"},
    },
    "required": ["verdict", "clause_id", "confidence"],
}

# per-process counters (spec: "per-process call counter exposed in the
# session report") -- only check_claim's real attempts count, not stub calls.
_stats = {"calls": 0, "errors": 0}
_quota_or_missing_model_logged = False


def get_call_stats() -> dict:
    return dict(_stats)


def _log_quota_or_missing_model_once(error_msg: str) -> None:
    # ponytail: log-once guard, same shape as the "claim check disabled" log
    # below -- avoids spamming logs every finalized turn during a rate-limited
    # or misconfigured demo. Never treated as evidence of a violation.
    global _quota_or_missing_model_logged
    if not _quota_or_missing_model_logged:
        logger.warning("claim_check: rate-limited or model unavailable (%s); verdict stays unclear", error_msg)
        _quota_or_missing_model_logged = True


def _build_prompt(sentence: str, clauses: list[dict]) -> str:
    clause_lines = "\n".join(
        f'- id="{c["section_number"]}" title="{c["title"]}": {c["literal_text"]}'
        for c in clauses
    )
    return f"""You are a contract compliance checker reviewing one sentence from a sales call transcript against the signed contract's clauses.

Contract clauses:
{clause_lines}

Rep sentence: "{sentence}"

Decide whether the sentence CONTRADICTS a clause's literal terms.
- "contradiction": the sentence states or implies something that conflicts with one clause (wrong price, wrong seat count, wrong notice period, promises a term the clause forbids, etc). Paraphrases count ("knock ten percent off" contradicts "no verbal discounting").
- "consistent": the sentence matches or is compatible with one clause's literal terms.
- "unclear": off-topic small talk, vague/hedged language with no concrete claim, or doesn't clearly match any clause.

Rules:
- If verdict is "contradiction" or "consistent", clause_id MUST be exactly one of the id values shown above.
- If verdict is "unclear", clause_id MUST be null.
- confidence is a number from 0.0 to 1.0: your certainty in the verdict.

Respond with ONLY the JSON object matching the schema. Do not invent or quote clause wording beyond the ids given."""


def check_claim(
    sentence: str,
    clauses: list[dict],
    *,
    client: Any = None,
    model: Optional[str] = None,
) -> dict:
    """Check one rep sentence against contract clauses for contradiction.

    Never raises. On any error (network, timeout, 429, bad JSON, schema
    mismatch) returns verdict "unclear" with `error` set - accuse-only-on-
    positive-evidence: an error is never treated as evidence of a violation.
    """
    model = model or DEFAULT_MODEL
    _stats["calls"] += 1
    t0 = time.monotonic()
    valid_ids = {c["section_number"] for c in clauses}
    result: dict = {
        "verdict": "unclear",
        "clause_id": None,
        "confidence": 0.0,
        "latency_ms": 0.0,
        "model": model,
        "error": None,
    }
    try:
        if client is None:
            from google import genai

            key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
            if not key:
                raise RuntimeError("no GEMINI_API_KEY/GOOGLE_API_KEY set in environment")
            client = genai.Client(api_key=key)  # ponytail: key never stored on result/log

        from google.genai import types

        response = client.models.generate_content(
            model=model,
            contents=_build_prompt(sentence, clauses),
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=_RESPONSE_SCHEMA,
                temperature=0,
                http_options=types.HttpOptions(timeout=TIMEOUT_MS),
            ),
        )
        data = json.loads(response.text)

        verdict = data.get("verdict")
        clause_id = data.get("clause_id")
        try:
            confidence = float(data.get("confidence", 0.0))
        except (TypeError, ValueError):
            confidence = 0.0
        confidence = max(0.0, min(1.0, confidence))

        if verdict not in _VERDICTS:
            verdict, clause_id = "unclear", None
        if clause_id not in valid_ids:
            clause_id = None
            if verdict != "unclear":
                verdict = "unclear"
        if verdict == "contradiction" and confidence < CONFIDENCE_MIN:
            verdict = "unclear"

        result["verdict"] = verdict
        result["clause_id"] = clause_id
        result["confidence"] = confidence
    except Exception as exc:  # noqa: BLE001 - intentional catch-all, see docstring
        _stats["errors"] += 1
        result["verdict"] = "unclear"
        result["clause_id"] = None
        result["confidence"] = 0.0
        error_msg = f"{type(exc).__name__}: {exc}"
        result["error"] = error_msg
        if "429" in error_msg or "404" in error_msg:
            _log_quota_or_missing_model_once(error_msg)
    finally:
        result["latency_ms"] = (time.monotonic() - t0) * 1000.0
    return result


# ---------------------------------------------------------------------------
# Default checker selection (consumed by server/main.py's get_claim_checker
# FastAPI dependency)
# ---------------------------------------------------------------------------
_disabled_logged = False


def _stub_claim_checker(sentence: str, clauses: list[dict]) -> dict:
    global _disabled_logged
    if not _disabled_logged:
        logger.info("claim check disabled")
        _disabled_logged = True
    return {
        "verdict": "unclear",
        "clause_id": None,
        "confidence": 0.0,
        "latency_ms": 0.0,
        "model": None,
        "error": None,
    }


def get_claim_checker() -> Callable[[str, list[dict]], dict]:
    """Real check_claim only when explicitly enabled AND a Gemini key exists;
    else a stub that always returns unclear (logged once)."""
    key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if os.environ.get("CLAUSECATCHER_CLAIM_CHECK") == "gemini" and key:
        return check_claim
    return _stub_claim_checker


def demo() -> None:
    """ponytail self-check: no network, uses a stub client."""

    class _Resp:
        def __init__(self, text):
            self.text = text

    class _Models:
        def generate_content(self, model, contents, config):
            return _Resp(json.dumps({"verdict": "contradiction", "clause_id": "3.1", "confidence": 0.95}))

    class _Client:
        models = _Models()

    clauses = [{"section_number": "3.1", "title": "Pricing", "literal_text": "Flat $48,000, no discounting."}]
    calls_before = get_call_stats()["calls"]
    out = check_claim("We'll knock ten percent off.", clauses, client=_Client())
    assert out["verdict"] == "contradiction"
    assert out["clause_id"] == "3.1"
    assert out["error"] is None
    assert get_call_stats()["calls"] == calls_before + 1

    # bad clause_id -> unclear
    class _Models2:
        def generate_content(self, model, contents, config):
            return _Resp(json.dumps({"verdict": "contradiction", "clause_id": "9.9", "confidence": 0.9}))

    class _Client2:
        models = _Models2()

    out2 = check_claim("x", clauses, client=_Client2())
    assert out2["verdict"] == "unclear" and out2["clause_id"] is None

    # exception -> unclear + error, no raise, error counter bumps
    class _Models3:
        def generate_content(self, model, contents, config):
            raise TimeoutError("boom")

    class _Client3:
        models = _Models3()

    errors_before = get_call_stats()["errors"]
    out3 = check_claim("x", clauses, client=_Client3())
    assert out3["verdict"] == "unclear" and out3["error"] is not None
    assert get_call_stats()["errors"] == errors_before + 1

    # 429-shaped exception -> unclear, still no raise
    class _Models4:
        def generate_content(self, model, contents, config):
            raise RuntimeError("429 quota exceeded")

    class _Client4:
        models = _Models4()

    out4 = check_claim("x", clauses, client=_Client4())
    assert out4["verdict"] == "unclear" and out4["error"] is not None

    # get_claim_checker gating: disabled by default (no env set)
    os.environ.pop("CLAUSECATCHER_CLAIM_CHECK", None)
    old_key = os.environ.pop("GEMINI_API_KEY", None)
    try:
        assert get_claim_checker() is _stub_claim_checker
        os.environ["CLAUSECATCHER_CLAIM_CHECK"] = "gemini"
        assert get_claim_checker() is _stub_claim_checker  # still no key -> stub
        os.environ["GEMINI_API_KEY"] = "fake-for-demo-only"
        assert get_claim_checker() is check_claim
    finally:
        os.environ.pop("CLAUSECATCHER_CLAIM_CHECK", None)
        if old_key is None:
            os.environ.pop("GEMINI_API_KEY", None)
        else:
            os.environ["GEMINI_API_KEY"] = old_key

    print("claim_check.py demo: OK")


if __name__ == "__main__":
    demo()
